
/* Automatically generated struct definitions for the Data API.
 * Do not edit manually, changes will be overwritten.           */

#define RNA_RUNTIME

#include <float.h>
#include <stdio.h>
#include <limits.h>
#include <string.h>

#include <stddef.h>

#include "MEM_guardedalloc.h"

#include "DNA_ID.h"
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"

#include "BLI_utildefines.h"

#include "BKE_context.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "RNA_define.h"
#include "RNA_types.h"
#include "rna_internal.h"

#include "rna_prototypes_gen.h"

#include "rna_depsgraph.c"

/* Autogenerated Functions */


CollectionPropertyRNA rna_Depsgraph_rna_properties;
PointerPropertyRNA rna_Depsgraph_rna_type;

extern FunctionRNA rna_Depsgraph_debug_relations_graphviz_func;
extern StringPropertyRNA rna_Depsgraph_debug_relations_graphviz_filename;

extern FunctionRNA rna_Depsgraph_debug_stats_gnuplot_func;
extern StringPropertyRNA rna_Depsgraph_debug_stats_gnuplot_filename;
extern StringPropertyRNA rna_Depsgraph_debug_stats_gnuplot_output_filename;

extern FunctionRNA rna_Depsgraph_debug_tag_update_func;
extern FunctionRNA rna_Depsgraph_debug_stats_func;
extern StringPropertyRNA rna_Depsgraph_debug_stats_result;


static PointerRNA Depsgraph_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void Depsgraph_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_Depsgraph_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = Depsgraph_rna_properties_get(iter);
}

void Depsgraph_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = Depsgraph_rna_properties_get(iter);
}

void Depsgraph_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int Depsgraph_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA Depsgraph_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

void Depsgraph_debug_relations_graphviz(struct Depsgraph *_self, const char * filename)
{
	rna_Depsgraph_debug_relations_graphviz(_self, filename);
}

void Depsgraph_debug_relations_graphviz_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct Depsgraph *_self;
	const char * filename;
	char *_data;
	
	_self = (struct Depsgraph *)_ptr->data;
	_data = (char *)_parms->data;
	filename = *((const char * *)_data);
	
	rna_Depsgraph_debug_relations_graphviz(_self, filename);
}

void Depsgraph_debug_stats_gnuplot(struct Depsgraph *_self, const char * filename, const char * output_filename)
{
	rna_Depsgraph_debug_stats_gnuplot(_self, filename, output_filename);
}

void Depsgraph_debug_stats_gnuplot_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct Depsgraph *_self;
	const char * filename;
	const char * output_filename;
	char *_data;
	
	_self = (struct Depsgraph *)_ptr->data;
	_data = (char *)_parms->data;
	filename = *((const char * *)_data);
	_data += 8;
	output_filename = *((const char * *)_data);
	
	rna_Depsgraph_debug_stats_gnuplot(_self, filename, output_filename);
}

void Depsgraph_debug_tag_update(struct Depsgraph *_self)
{
	rna_Depsgraph_debug_tag_update(_self);
}

void Depsgraph_debug_tag_update_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct Depsgraph *_self;
	_self = (struct Depsgraph *)_ptr->data;
	
	rna_Depsgraph_debug_tag_update(_self);
}

void Depsgraph_debug_stats(struct Depsgraph *_self, char * result)
{
	rna_Depsgraph_debug_stats(_self, result);
}

void Depsgraph_debug_stats_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct Depsgraph *_self;
	char * result;
	char *_data;
	
	_self = (struct Depsgraph *)_ptr->data;
	_data = (char *)_parms->data;
	result = ((char * )_data);
	
	rna_Depsgraph_debug_stats(_self, result);
}

/* Repeated prototypes to detect errors */

void rna_Depsgraph_debug_relations_graphviz(struct Depsgraph *_self, const char * filename);
void rna_Depsgraph_debug_stats_gnuplot(struct Depsgraph *_self, const char * filename, const char * output_filename);
void rna_Depsgraph_debug_tag_update(struct Depsgraph *_self);
void rna_Depsgraph_debug_stats(struct Depsgraph *_self, char * result);

/* Dependency Graph */
CollectionPropertyRNA rna_Depsgraph_rna_properties = {
	{(PropertyRNA *)&rna_Depsgraph_rna_type, NULL,
	-1, "rna_properties", 0, 0, 1, 0, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	Depsgraph_rna_properties_begin, Depsgraph_rna_properties_next, Depsgraph_rna_properties_end, Depsgraph_rna_properties_get, NULL, NULL, Depsgraph_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_Depsgraph_rna_type = {
	{NULL, (PropertyRNA *)&rna_Depsgraph_rna_properties,
	-1, "rna_type", 8912896, 0, 0, 0, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	Depsgraph_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

StringPropertyRNA rna_Depsgraph_debug_relations_graphviz_filename = {
	{NULL, NULL,
	-1, "filename", 262145, 1, 0, 0, "File Name",
	"File in which to store graphviz debug output",
	0, "*",
	PROP_STRING, PROP_FILEPATH | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, 1024, ""
};

FunctionRNA rna_Depsgraph_debug_relations_graphviz_func = {
	{(FunctionRNA *)&rna_Depsgraph_debug_stats_gnuplot_func, NULL,
	NULL,
	{(PropertyRNA *)&rna_Depsgraph_debug_relations_graphviz_filename, (PropertyRNA *)&rna_Depsgraph_debug_relations_graphviz_filename}},
	"debug_relations_graphviz", 0, "debug_relations_graphviz",
	Depsgraph_debug_relations_graphviz_call,
	NULL
};

StringPropertyRNA rna_Depsgraph_debug_stats_gnuplot_filename = {
	{(PropertyRNA *)&rna_Depsgraph_debug_stats_gnuplot_output_filename, NULL,
	-1, "filename", 262145, 1, 0, 0, "File Name",
	"File in which to store graphviz debug output",
	0, "*",
	PROP_STRING, PROP_FILEPATH | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, 1024, ""
};

StringPropertyRNA rna_Depsgraph_debug_stats_gnuplot_output_filename = {
	{NULL, (PropertyRNA *)&rna_Depsgraph_debug_stats_gnuplot_filename,
	-1, "output_filename", 262145, 1, 0, 0, "Output File Name",
	"File name where gnuplot script will save the result",
	0, "*",
	PROP_STRING, PROP_FILEPATH | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, 1024, ""
};

FunctionRNA rna_Depsgraph_debug_stats_gnuplot_func = {
	{(FunctionRNA *)&rna_Depsgraph_debug_tag_update_func, (FunctionRNA *)&rna_Depsgraph_debug_relations_graphviz_func,
	NULL,
	{(PropertyRNA *)&rna_Depsgraph_debug_stats_gnuplot_filename, (PropertyRNA *)&rna_Depsgraph_debug_stats_gnuplot_output_filename}},
	"debug_stats_gnuplot", 0, "debug_stats_gnuplot",
	Depsgraph_debug_stats_gnuplot_call,
	NULL
};

FunctionRNA rna_Depsgraph_debug_tag_update_func = {
	{(FunctionRNA *)&rna_Depsgraph_debug_stats_func, (FunctionRNA *)&rna_Depsgraph_debug_stats_gnuplot_func,
	NULL,
	{NULL, NULL}},
	"debug_tag_update", 0, "debug_tag_update",
	Depsgraph_debug_tag_update_call,
	NULL
};

StringPropertyRNA rna_Depsgraph_debug_stats_result = {
	{NULL, NULL,
	-1, "result", 8650753, 2, 0, 0, "result",
	"",
	0, "*",
	PROP_STRING, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, 16384, ""
};

FunctionRNA rna_Depsgraph_debug_stats_func = {
	{NULL, (FunctionRNA *)&rna_Depsgraph_debug_tag_update_func,
	NULL,
	{(PropertyRNA *)&rna_Depsgraph_debug_stats_result, (PropertyRNA *)&rna_Depsgraph_debug_stats_result}},
	"debug_stats", 0, "Report the number of elements in the Dependency Graph",
	Depsgraph_debug_stats_call,
	NULL
};

StructRNA RNA_Depsgraph = {
	{(ContainerRNA *)&RNA_DynamicPaintCanvasSettings, (ContainerRNA *)&RNA_SplineBezierPoints,
	NULL,
	{(PropertyRNA *)&rna_Depsgraph_rna_properties, (PropertyRNA *)&rna_Depsgraph_rna_type}},
	"Depsgraph", NULL, NULL, 516, NULL, "Dependency Graph",
	"",
	"*", 17,
	NULL, (PropertyRNA *)&rna_Depsgraph_rna_properties,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{(FunctionRNA *)&rna_Depsgraph_debug_relations_graphviz_func, (FunctionRNA *)&rna_Depsgraph_debug_stats_func}
};

