
/* Automatically generated struct definitions for the Data API.
 * Do not edit manually, changes will be overwritten.           */

#define RNA_RUNTIME

#include <float.h>
#include <stdio.h>
#include <limits.h>
#include <string.h>

#include <stddef.h>

#include "MEM_guardedalloc.h"

#include "DNA_ID.h"
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"

#include "BLI_utildefines.h"

#include "BKE_context.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "RNA_define.h"
#include "RNA_types.h"
#include "rna_internal.h"

#include "rna_prototypes_gen.h"

#include "rna_python_component.c"

/* Autogenerated Functions */


CollectionPropertyRNA rna_PythonComponent_rna_properties;
PointerPropertyRNA rna_PythonComponent_rna_type;
StringPropertyRNA rna_PythonComponent_name;
StringPropertyRNA rna_PythonComponent_module;
BoolPropertyRNA rna_PythonComponent_show_expanded;
CollectionPropertyRNA rna_PythonComponent_properties;


CollectionPropertyRNA rna_PythonComponentProperty_rna_properties;
PointerPropertyRNA rna_PythonComponentProperty_rna_type;
StringPropertyRNA rna_PythonComponentProperty_name;


extern CollectionPropertyRNA rna_PythonComponentProperty_rna_properties;
extern PointerPropertyRNA rna_PythonComponentProperty_rna_type;
extern StringPropertyRNA rna_PythonComponentProperty_name;

BoolPropertyRNA rna_ComponentBooleanProperty_value;


extern CollectionPropertyRNA rna_PythonComponentProperty_rna_properties;
extern PointerPropertyRNA rna_PythonComponentProperty_rna_type;
extern StringPropertyRNA rna_PythonComponentProperty_name;

IntPropertyRNA rna_ComponentIntProperty_value;


extern CollectionPropertyRNA rna_PythonComponentProperty_rna_properties;
extern PointerPropertyRNA rna_PythonComponentProperty_rna_type;
extern StringPropertyRNA rna_PythonComponentProperty_name;

FloatPropertyRNA rna_ComponentFloatProperty_value;


extern CollectionPropertyRNA rna_PythonComponentProperty_rna_properties;
extern PointerPropertyRNA rna_PythonComponentProperty_rna_type;
extern StringPropertyRNA rna_PythonComponentProperty_name;

StringPropertyRNA rna_ComponentStringProperty_value;


extern CollectionPropertyRNA rna_PythonComponentProperty_rna_properties;
extern PointerPropertyRNA rna_PythonComponentProperty_rna_type;
extern StringPropertyRNA rna_PythonComponentProperty_name;

EnumPropertyRNA rna_ComponentSetProperty_value;


extern CollectionPropertyRNA rna_PythonComponentProperty_rna_properties;
extern PointerPropertyRNA rna_PythonComponentProperty_rna_type;
extern StringPropertyRNA rna_PythonComponentProperty_name;

FloatPropertyRNA rna_ComponentVector2DProperty_value;


extern CollectionPropertyRNA rna_PythonComponentProperty_rna_properties;
extern PointerPropertyRNA rna_PythonComponentProperty_rna_type;
extern StringPropertyRNA rna_PythonComponentProperty_name;

FloatPropertyRNA rna_ComponentVector3DProperty_value;


extern CollectionPropertyRNA rna_PythonComponentProperty_rna_properties;
extern PointerPropertyRNA rna_PythonComponentProperty_rna_type;
extern StringPropertyRNA rna_PythonComponentProperty_name;

FloatPropertyRNA rna_ComponentVector4DProperty_value;


extern CollectionPropertyRNA rna_PythonComponentProperty_rna_properties;
extern PointerPropertyRNA rna_PythonComponentProperty_rna_type;
extern StringPropertyRNA rna_PythonComponentProperty_name;

FloatPropertyRNA rna_ComponentColor3Property_value;


extern CollectionPropertyRNA rna_PythonComponentProperty_rna_properties;
extern PointerPropertyRNA rna_PythonComponentProperty_rna_type;
extern StringPropertyRNA rna_PythonComponentProperty_name;

FloatPropertyRNA rna_ComponentColor4Property_value;

static PointerRNA PythonComponent_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void PythonComponent_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_PythonComponent_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = PythonComponent_rna_properties_get(iter);
}

void PythonComponent_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = PythonComponent_rna_properties_get(iter);
}

void PythonComponent_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int PythonComponent_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA PythonComponent_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

void PythonComponent_name_get(PointerRNA *ptr, char *value)
{
	PythonComponent *data = (PythonComponent *)(ptr->data);
	BLI_strncpy_utf8(value, data->name, 1024);
}

int PythonComponent_name_length(PointerRNA *ptr)
{
	PythonComponent *data = (PythonComponent *)(ptr->data);
	return strlen(data->name);
}

void PythonComponent_module_get(PointerRNA *ptr, char *value)
{
	PythonComponent *data = (PythonComponent *)(ptr->data);
	BLI_strncpy_utf8(value, data->module, 1024);
}

int PythonComponent_module_length(PointerRNA *ptr)
{
	PythonComponent *data = (PythonComponent *)(ptr->data);
	return strlen(data->module);
}

bool PythonComponent_show_expanded_get(PointerRNA *ptr)
{
	PythonComponent *data = (PythonComponent *)(ptr->data);
	return (((data->flag) & 1) != 0);
}

void PythonComponent_show_expanded_set(PointerRNA *ptr, bool value)
{
	PythonComponent *data = (PythonComponent *)(ptr->data);
	if (value) data->flag |= 1;
	else data->flag &= ~1;
}

static PointerRNA PythonComponent_properties_get(CollectionPropertyIterator *iter)
{
	return rna_pointer_inherit_refine(&iter->parent, &RNA_PythonComponentProperty, rna_iterator_listbase_get(iter));
}

void PythonComponent_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{
	PythonComponent *data = (PythonComponent *)(ptr->data);

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_PythonComponent_properties;

	rna_iterator_listbase_begin(iter, &data->properties, NULL);

	if (iter->valid)
		iter->ptr = PythonComponent_properties_get(iter);
}

void PythonComponent_properties_next(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_next(iter);

	if (iter->valid)
		iter->ptr = PythonComponent_properties_get(iter);
}

void PythonComponent_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int PythonComponent_properties_lookup_int(PointerRNA *ptr, int index, PointerRNA *r_ptr)
{
	int found = 0;
	CollectionPropertyIterator iter;

	PythonComponent_properties_begin(&iter, ptr);

	if (iter.valid) {
		ListBaseIterator *internal = &iter.internal.listbase;
		if (internal->skip) {
			while (index-- > 0 && iter.valid) {
				rna_iterator_listbase_next(&iter);
			}
			found = (index == -1 && iter.valid);
		}
		else {
			while (index-- > 0 && internal->link)
				internal->link = internal->link->next;
			found = (index == -1 && internal->link);
		}
		if (found) *r_ptr = PythonComponent_properties_get(&iter);
	}

	PythonComponent_properties_end(&iter);

	return found;
}

int PythonComponent_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	extern int PythonComponentProperty_name_length(PointerRNA *);
	extern void PythonComponentProperty_name_get(PointerRNA *, char *);

	bool found = false;
	CollectionPropertyIterator iter;
	char namebuf[1024];
	char *name;

	PythonComponent_properties_begin(&iter, ptr);

	while (iter.valid) {
		if (iter.ptr.data) {
			int namelen = PythonComponentProperty_name_length(&iter.ptr);
			if (namelen < 1024) {
				PythonComponentProperty_name_get(&iter.ptr, namebuf);
				if (strcmp(namebuf, key) == 0) {
					found = true;
					*r_ptr = iter.ptr;
					break;
				}
			}
			else {
				name = MEM_mallocN(namelen+1, "name string");
				PythonComponentProperty_name_get(&iter.ptr, name);
				if (strcmp(name, key) == 0) {
					MEM_freeN(name);

					found = true;
					*r_ptr = iter.ptr;
					break;
				}
				else {
					MEM_freeN(name);
				}
			}
		}
		PythonComponent_properties_next(&iter);
	}
	PythonComponent_properties_end(&iter);

	return found;
}

static PointerRNA PythonComponentProperty_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void PythonComponentProperty_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_PythonComponentProperty_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = PythonComponentProperty_rna_properties_get(iter);
}

void PythonComponentProperty_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = PythonComponentProperty_rna_properties_get(iter);
}

void PythonComponentProperty_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int PythonComponentProperty_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA PythonComponentProperty_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

void PythonComponentProperty_name_get(PointerRNA *ptr, char *value)
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	BLI_strncpy_utf8(value, data->name, 128);
}

int PythonComponentProperty_name_length(PointerRNA *ptr)
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	return strlen(data->name);
}

bool ComponentBooleanProperty_value_get(PointerRNA *ptr)
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	return (((data->boolval) & 1) != 0);
}

void ComponentBooleanProperty_value_set(PointerRNA *ptr, bool value)
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	if (value) data->boolval |= 1;
	else data->boolval &= ~1;
}

int ComponentIntProperty_value_get(PointerRNA *ptr)
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	return (int)(data->intval);
}

void ComponentIntProperty_value_set(PointerRNA *ptr, int value)
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	data->intval = value;
}

float ComponentFloatProperty_value_get(PointerRNA *ptr)
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	return (float)(data->floatval);
}

void ComponentFloatProperty_value_set(PointerRNA *ptr, float value)
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	data->floatval = value;
}

void ComponentStringProperty_value_get(PointerRNA *ptr, char *value)
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	BLI_strncpy_utf8(value, data->strval, 128);
}

int ComponentStringProperty_value_length(PointerRNA *ptr)
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	return strlen(data->strval);
}

void ComponentStringProperty_value_set(PointerRNA *ptr, const char *value)
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	BLI_strncpy_utf8(data->strval, value, 128);
}

int ComponentSetProperty_value_get(PointerRNA *ptr)
{
	return rna_ComponentSetProperty_get(ptr);
}

void ComponentSetProperty_value_set(PointerRNA *ptr, int value)
{
	rna_ComponentSetProperty_set(ptr, value);
}

void ComponentVector2DProperty_value_get(PointerRNA *ptr, float values[2])
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 2; i++) {
		values[i] = (float)(((float *)data->vec)[i]);
	}
}

void ComponentVector2DProperty_value_set(PointerRNA *ptr, const float values[2])
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 2; i++) {
		((float *)data->vec)[i] = values[i];
	}
}

void ComponentVector3DProperty_value_get(PointerRNA *ptr, float values[3])
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		values[i] = (float)(((float *)data->vec)[i]);
	}
}

void ComponentVector3DProperty_value_set(PointerRNA *ptr, const float values[3])
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		((float *)data->vec)[i] = values[i];
	}
}

void ComponentVector4DProperty_value_get(PointerRNA *ptr, float values[4])
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 4; i++) {
		values[i] = (float)(((float *)data->vec)[i]);
	}
}

void ComponentVector4DProperty_value_set(PointerRNA *ptr, const float values[4])
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 4; i++) {
		((float *)data->vec)[i] = values[i];
	}
}

void ComponentColor3Property_value_get(PointerRNA *ptr, float values[3])
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		values[i] = (float)(((float *)data->vec)[i]);
	}
}

void ComponentColor3Property_value_set(PointerRNA *ptr, const float values[3])
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		((float *)data->vec)[i] = CLAMPIS(values[i], 0.0f, FLT_MAX);
	}
}

void ComponentColor4Property_value_get(PointerRNA *ptr, float values[4])
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 4; i++) {
		values[i] = (float)(((float *)data->vec)[i]);
	}
}

void ComponentColor4Property_value_set(PointerRNA *ptr, const float values[4])
{
	PythonComponentProperty *data = (PythonComponentProperty *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 4; i++) {
		((float *)data->vec)[i] = CLAMPIS(values[i], 0.0f, FLT_MAX);
	}
}













/* Python Component */
CollectionPropertyRNA rna_PythonComponent_rna_properties = {
	{(PropertyRNA *)&rna_PythonComponent_rna_type, NULL,
	-1, "rna_properties", 0, 0, 1, 0, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	PythonComponent_rna_properties_begin, PythonComponent_rna_properties_next, PythonComponent_rna_properties_end, PythonComponent_rna_properties_get, NULL, NULL, PythonComponent_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_PythonComponent_rna_type = {
	{(PropertyRNA *)&rna_PythonComponent_name, (PropertyRNA *)&rna_PythonComponent_rna_properties,
	-1, "rna_type", 8912896, 0, 0, 0, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	PythonComponent_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

StringPropertyRNA rna_PythonComponent_name = {
	{(PropertyRNA *)&rna_PythonComponent_module, (PropertyRNA *)&rna_PythonComponent_rna_type,
	-1, "name", 262144, 0, 0, 0, "Name",
	"",
	0, "*",
	PROP_STRING, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {1024, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	PythonComponent_name_get, PythonComponent_name_length, NULL, NULL, NULL, NULL, 1024, ""
};

StringPropertyRNA rna_PythonComponent_module = {
	{(PropertyRNA *)&rna_PythonComponent_show_expanded, (PropertyRNA *)&rna_PythonComponent_name,
	-1, "module", 262144, 0, 0, 0, "Module",
	"",
	0, "*",
	PROP_STRING, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {1024, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	PythonComponent_module_get, PythonComponent_module_length, NULL, NULL, NULL, NULL, 1024, ""
};

BoolPropertyRNA rna_PythonComponent_show_expanded = {
	{(PropertyRNA *)&rna_PythonComponent_properties, (PropertyRNA *)&rna_PythonComponent_module,
	-1, "show_expanded", 4099, 0, 0, 0, "Expanded",
	"Set sensor expanded in the user interface",
	4, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	PythonComponent_show_expanded_get, PythonComponent_show_expanded_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

CollectionPropertyRNA rna_PythonComponent_properties = {
	{NULL, (PropertyRNA *)&rna_PythonComponent_show_expanded,
	-1, "properties", 0, 0, 0, 0, "Properties",
	"Component properties",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	PythonComponent_properties_begin, PythonComponent_properties_next, PythonComponent_properties_end, PythonComponent_properties_get, NULL, PythonComponent_properties_lookup_int, PythonComponent_properties_lookup_string, NULL, &RNA_PythonComponentProperty
};

StructRNA RNA_PythonComponent = {
	{(ContainerRNA *)&RNA_PythonComponentProperty, (ContainerRNA *)&RNA_BoneGroup,
	NULL,
	{(PropertyRNA *)&rna_PythonComponent_rna_properties, (PropertyRNA *)&rna_PythonComponent_properties}},
	"PythonComponent", NULL, NULL, 516, NULL, "Python Component",
	"",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponent_module, (PropertyRNA *)&rna_PythonComponent_rna_properties,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Component Property */
CollectionPropertyRNA rna_PythonComponentProperty_rna_properties = {
	{(PropertyRNA *)&rna_PythonComponentProperty_rna_type, NULL,
	-1, "rna_properties", 0, 0, 1, 0, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	PythonComponentProperty_rna_properties_begin, PythonComponentProperty_rna_properties_next, PythonComponentProperty_rna_properties_end, PythonComponentProperty_rna_properties_get, NULL, NULL, PythonComponentProperty_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_PythonComponentProperty_rna_type = {
	{(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	-1, "rna_type", 8912896, 0, 0, 0, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	PythonComponentProperty_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

StringPropertyRNA rna_PythonComponentProperty_name = {
	{NULL, (PropertyRNA *)&rna_PythonComponentProperty_rna_type,
	-1, "name", 262144, 0, 0, 0, "Name",
	"",
	0, "*",
	PROP_STRING, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {128, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	PythonComponentProperty_name_get, PythonComponentProperty_name_length, NULL, NULL, NULL, NULL, 128, ""
};

StructRNA RNA_PythonComponentProperty = {
	{(ContainerRNA *)&RNA_ComponentBooleanProperty, (ContainerRNA *)&RNA_PythonComponent,
	NULL,
	{(PropertyRNA *)&rna_PythonComponentProperty_rna_properties, (PropertyRNA *)&rna_PythonComponentProperty_name}},
	"PythonComponentProperty", NULL, NULL, 516, NULL, "Python Component Property",
	"A property of a Python Component",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	NULL,
	NULL,
	rna_PythonComponentProperty_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Component Boolean Property */
BoolPropertyRNA rna_ComponentBooleanProperty_value = {
	{NULL, NULL,
	-1, "value", 3, 0, 0, 0, "Value",
	"Property value",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	ComponentBooleanProperty_value_get, ComponentBooleanProperty_value_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

StructRNA RNA_ComponentBooleanProperty = {
	{(ContainerRNA *)&RNA_ComponentIntProperty, (ContainerRNA *)&RNA_PythonComponentProperty,
	NULL,
	{(PropertyRNA *)&rna_ComponentBooleanProperty_value, (PropertyRNA *)&rna_ComponentBooleanProperty_value}},
	"ComponentBooleanProperty", NULL, NULL, 516, NULL, "Python Component Boolean Property",
	"A boolean property of a Python Component",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	&RNA_PythonComponentProperty,
	NULL,
	rna_PythonComponentProperty_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Component Integer Property */
IntPropertyRNA rna_ComponentIntProperty_value = {
	{NULL, NULL,
	-1, "value", 3, 0, 4, 0, "Value",
	"Property value",
	0, "*",
	PROP_INT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	offsetof(PythonComponentProperty, intval), 0, NULL},
	ComponentIntProperty_value_get, ComponentIntProperty_value_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
	-10000, 10000, INT_MIN, INT_MAX, 1, 0, NULL
};

StructRNA RNA_ComponentIntProperty = {
	{(ContainerRNA *)&RNA_ComponentFloatProperty, (ContainerRNA *)&RNA_ComponentBooleanProperty,
	NULL,
	{(PropertyRNA *)&rna_ComponentIntProperty_value, (PropertyRNA *)&rna_ComponentIntProperty_value}},
	"ComponentIntProperty", NULL, NULL, 516, NULL, "Python Component Integer Property",
	"An integer property of a Python Component",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	&RNA_PythonComponentProperty,
	NULL,
	rna_PythonComponentProperty_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Component Float Property */
FloatPropertyRNA rna_ComponentFloatProperty_value = {
	{NULL, NULL,
	-1, "value", 3, 0, 4, 0, "Value",
	"Property value",
	0, "*",
	PROP_FLOAT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	offsetof(PythonComponentProperty, floatval), 5, NULL},
	ComponentFloatProperty_value_get, ComponentFloatProperty_value_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, NULL
};

StructRNA RNA_ComponentFloatProperty = {
	{(ContainerRNA *)&RNA_ComponentStringProperty, (ContainerRNA *)&RNA_ComponentIntProperty,
	NULL,
	{(PropertyRNA *)&rna_ComponentFloatProperty_value, (PropertyRNA *)&rna_ComponentFloatProperty_value}},
	"ComponentFloatProperty", NULL, NULL, 516, NULL, "Python Component Float Property",
	"A float property of a Python Component",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	&RNA_PythonComponentProperty,
	NULL,
	rna_PythonComponentProperty_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Component String Property */
StringPropertyRNA rna_ComponentStringProperty_value = {
	{NULL, NULL,
	-1, "value", 262145, 0, 0, 0, "Value",
	"Property value",
	0, "*",
	PROP_STRING, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {128, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	ComponentStringProperty_value_get, ComponentStringProperty_value_length, ComponentStringProperty_value_set, NULL, NULL, NULL, 128, ""
};

StructRNA RNA_ComponentStringProperty = {
	{(ContainerRNA *)&RNA_ComponentSetProperty, (ContainerRNA *)&RNA_ComponentFloatProperty,
	NULL,
	{(PropertyRNA *)&rna_ComponentStringProperty_value, (PropertyRNA *)&rna_ComponentStringProperty_value}},
	"ComponentStringProperty", NULL, NULL, 516, NULL, "Python Component String Property",
	"A string property of a Python Component",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	&RNA_PythonComponentProperty,
	NULL,
	rna_PythonComponentProperty_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Component Set Property */
static const EnumPropertyItem rna_ComponentSetProperty_value_items[2] = {
	{0, "EMPTY", 0, "Empty", ""},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_ComponentSetProperty_value = {
	{NULL, NULL,
	-1, "value", 3, 0, 0, 0, "Value",
	"Property value",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	ComponentSetProperty_value_get, ComponentSetProperty_value_set, rna_ComponentSetProperty_itemf, NULL, NULL, NULL, rna_ComponentSetProperty_value_items, 1, 0
};

StructRNA RNA_ComponentSetProperty = {
	{(ContainerRNA *)&RNA_ComponentVector2DProperty, (ContainerRNA *)&RNA_ComponentStringProperty,
	NULL,
	{(PropertyRNA *)&rna_ComponentSetProperty_value, (PropertyRNA *)&rna_ComponentSetProperty_value}},
	"ComponentSetProperty", NULL, NULL, 516, NULL, "Python Component Set Property",
	"A set property of a Python Component",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	&RNA_PythonComponentProperty,
	NULL,
	rna_PythonComponentProperty_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Component Vector 2D Property */
static float rna_ComponentVector2DProperty_value_default[2] = {
	0.0f,
	0.0f
};

FloatPropertyRNA rna_ComponentVector2DProperty_value = {
	{NULL, NULL,
	-1, "value", 3, 0, 4, 0, "Value",
	"Property value",
	0, "*",
	PROP_FLOAT, PROP_COORDS | PROP_UNIT_NONE, NULL, 1, {2, 0, 0}, 2,
	NULL, 318767104, NULL, NULL,
	offsetof(PythonComponentProperty, vec), 5, NULL},
	NULL, NULL, ComponentVector2DProperty_value_get, ComponentVector2DProperty_value_set, NULL, NULL, NULL, NULL, NULL, NULL, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, rna_ComponentVector2DProperty_value_default
};

StructRNA RNA_ComponentVector2DProperty = {
	{(ContainerRNA *)&RNA_ComponentVector3DProperty, (ContainerRNA *)&RNA_ComponentSetProperty,
	NULL,
	{(PropertyRNA *)&rna_ComponentVector2DProperty_value, (PropertyRNA *)&rna_ComponentVector2DProperty_value}},
	"ComponentVector2DProperty", NULL, NULL, 516, NULL, "Python Component Vector 2D Property",
	"A 2D vector property of a Python Component",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	&RNA_PythonComponentProperty,
	NULL,
	rna_PythonComponentProperty_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Component Vector 3D Property */
static float rna_ComponentVector3DProperty_value_default[3] = {
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_ComponentVector3DProperty_value = {
	{NULL, NULL,
	-1, "value", 3, 0, 4, 0, "Value",
	"Property value",
	0, "*",
	PROP_FLOAT, PROP_COORDS | PROP_UNIT_NONE, NULL, 1, {3, 0, 0}, 3,
	NULL, 318767104, NULL, NULL,
	offsetof(PythonComponentProperty, vec), 5, NULL},
	NULL, NULL, ComponentVector3DProperty_value_get, ComponentVector3DProperty_value_set, NULL, NULL, NULL, NULL, NULL, NULL, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, rna_ComponentVector3DProperty_value_default
};

StructRNA RNA_ComponentVector3DProperty = {
	{(ContainerRNA *)&RNA_ComponentVector4DProperty, (ContainerRNA *)&RNA_ComponentVector2DProperty,
	NULL,
	{(PropertyRNA *)&rna_ComponentVector3DProperty_value, (PropertyRNA *)&rna_ComponentVector3DProperty_value}},
	"ComponentVector3DProperty", NULL, NULL, 516, NULL, "Python Component Vector 3D Property",
	"A 3D vector property of a Python Component",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	&RNA_PythonComponentProperty,
	NULL,
	rna_PythonComponentProperty_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Component Vector 4D Property */
static float rna_ComponentVector4DProperty_value_default[4] = {
	0.0f,
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_ComponentVector4DProperty_value = {
	{NULL, NULL,
	-1, "value", 3, 0, 4, 0, "Value",
	"Property value",
	0, "*",
	PROP_FLOAT, PROP_COORDS | PROP_UNIT_NONE, NULL, 1, {4, 0, 0}, 4,
	NULL, 318767104, NULL, NULL,
	offsetof(PythonComponentProperty, vec), 5, NULL},
	NULL, NULL, ComponentVector4DProperty_value_get, ComponentVector4DProperty_value_set, NULL, NULL, NULL, NULL, NULL, NULL, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, rna_ComponentVector4DProperty_value_default
};

StructRNA RNA_ComponentVector4DProperty = {
	{(ContainerRNA *)&RNA_ComponentColor3Property, (ContainerRNA *)&RNA_ComponentVector3DProperty,
	NULL,
	{(PropertyRNA *)&rna_ComponentVector4DProperty_value, (PropertyRNA *)&rna_ComponentVector4DProperty_value}},
	"ComponentVector4DProperty", NULL, NULL, 516, NULL, "Python Component Vector 4D Property",
	"A 4D vector property of a Python Component",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	&RNA_PythonComponentProperty,
	NULL,
	rna_PythonComponentProperty_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Component Color 3 Property */
static float rna_ComponentColor3Property_value_default[3] = {
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_ComponentColor3Property_value = {
	{NULL, NULL,
	-1, "value", 3, 0, 4, 0, "Value",
	"Property value",
	0, "*",
	PROP_FLOAT, PROP_COLOR | PROP_UNIT_NONE, NULL, 1, {3, 0, 0}, 3,
	NULL, 318767104, NULL, NULL,
	offsetof(PythonComponentProperty, vec), 5, NULL},
	NULL, NULL, ComponentColor3Property_value_get, ComponentColor3Property_value_set, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, FLT_MAX, 10.0f, 3, 0.0f, rna_ComponentColor3Property_value_default
};

StructRNA RNA_ComponentColor3Property = {
	{(ContainerRNA *)&RNA_ComponentColor4Property, (ContainerRNA *)&RNA_ComponentVector4DProperty,
	NULL,
	{(PropertyRNA *)&rna_ComponentColor3Property_value, (PropertyRNA *)&rna_ComponentColor3Property_value}},
	"ComponentColor3Property", NULL, NULL, 516, NULL, "Python Component Color 3 Property",
	"A 3 channels color property of a Python Component",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	&RNA_PythonComponentProperty,
	NULL,
	rna_PythonComponentProperty_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Component Color 4 Property */
static float rna_ComponentColor4Property_value_default[4] = {
	0.0f,
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_ComponentColor4Property_value = {
	{NULL, NULL,
	-1, "value", 3, 0, 4, 0, "Value",
	"Property value",
	0, "*",
	PROP_FLOAT, PROP_COLOR | PROP_UNIT_NONE, NULL, 1, {4, 0, 0}, 4,
	NULL, 318767104, NULL, NULL,
	offsetof(PythonComponentProperty, vec), 5, NULL},
	NULL, NULL, ComponentColor4Property_value_get, ComponentColor4Property_value_set, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, FLT_MAX, 10.0f, 3, 0.0f, rna_ComponentColor4Property_value_default
};

StructRNA RNA_ComponentColor4Property = {
	{(ContainerRNA *)&RNA_GameProperty, (ContainerRNA *)&RNA_ComponentColor3Property,
	NULL,
	{(PropertyRNA *)&rna_ComponentColor4Property_value, (PropertyRNA *)&rna_ComponentColor4Property_value}},
	"ComponentColor4Property", NULL, NULL, 516, NULL, "Python Component Color 4 Property",
	"A 4 channels color property of a Python Component",
	"*", 17,
	(PropertyRNA *)&rna_PythonComponentProperty_name, (PropertyRNA *)&rna_PythonComponentProperty_rna_properties,
	&RNA_PythonComponentProperty,
	NULL,
	rna_PythonComponentProperty_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

