
/* Automatically generated struct definitions for the Data API.
 * Do not edit manually, changes will be overwritten.           */

#define RNA_RUNTIME

#include <float.h>
#include <stdio.h>
#include <limits.h>
#include <string.h>

#include <stddef.h>

#include "MEM_guardedalloc.h"

#include "DNA_ID.h"
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"

#include "BLI_utildefines.h"

#include "BKE_context.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "RNA_define.h"
#include "RNA_types.h"
#include "rna_internal.h"

#include "rna_prototypes_gen.h"

#include "rna_camera.c"
#include "rna_camera_api.c"

/* Autogenerated Functions */


extern CollectionPropertyRNA rna_ID_rna_properties;
extern PointerPropertyRNA rna_ID_rna_type;
extern StringPropertyRNA rna_ID_name;
extern IntPropertyRNA rna_ID_users;
extern BoolPropertyRNA rna_ID_use_fake_user;
extern BoolPropertyRNA rna_ID_tag;
extern BoolPropertyRNA rna_ID_is_updated;
extern BoolPropertyRNA rna_ID_is_updated_data;
extern BoolPropertyRNA rna_ID_is_library_indirect;
extern PointerPropertyRNA rna_ID_library;
extern PointerPropertyRNA rna_ID_preview;

EnumPropertyRNA rna_Camera_type;
EnumPropertyRNA rna_Camera_show_guide;
EnumPropertyRNA rna_Camera_sensor_fit;
FloatPropertyRNA rna_Camera_passepartout_alpha;
FloatPropertyRNA rna_Camera_angle_x;
FloatPropertyRNA rna_Camera_angle_y;
FloatPropertyRNA rna_Camera_angle;
FloatPropertyRNA rna_Camera_clip_start;
FloatPropertyRNA rna_Camera_clip_end;
FloatPropertyRNA rna_Camera_lens;
FloatPropertyRNA rna_Camera_sensor_width;
FloatPropertyRNA rna_Camera_sensor_height;
FloatPropertyRNA rna_Camera_ortho_scale;
FloatPropertyRNA rna_Camera_draw_size;
FloatPropertyRNA rna_Camera_shift_x;
FloatPropertyRNA rna_Camera_shift_y;
FloatPropertyRNA rna_Camera_dof_distance;
FloatPropertyRNA rna_Camera_lod_factor;
PointerPropertyRNA rna_Camera_stereo;
PointerPropertyRNA rna_Camera_viewport;
BoolPropertyRNA rna_Camera_override_culling;
BoolPropertyRNA rna_Camera_show_frustum;
BoolPropertyRNA rna_Camera_use_viewport;
BoolPropertyRNA rna_Camera_use_object_activity_culling;
BoolPropertyRNA rna_Camera_show_limits;
BoolPropertyRNA rna_Camera_show_mist;
BoolPropertyRNA rna_Camera_show_passepartout;
BoolPropertyRNA rna_Camera_show_safe_areas;
BoolPropertyRNA rna_Camera_show_safe_center;
BoolPropertyRNA rna_Camera_show_name;
BoolPropertyRNA rna_Camera_show_sensor;
EnumPropertyRNA rna_Camera_lens_unit;
PointerPropertyRNA rna_Camera_dof_object;
PointerPropertyRNA rna_Camera_gpu_dof;
PointerPropertyRNA rna_Camera_animation_data;

extern FunctionRNA rna_ID_copy_func;
extern PointerPropertyRNA rna_ID_copy_id;

extern FunctionRNA rna_ID_user_clear_func;
extern FunctionRNA rna_ID_user_remap_func;
extern PointerPropertyRNA rna_ID_user_remap_new_id;

extern FunctionRNA rna_ID_make_local_func;
extern BoolPropertyRNA rna_ID_make_local_clear_proxy;
extern PointerPropertyRNA rna_ID_make_local_id;

extern FunctionRNA rna_ID_user_of_id_func;
extern PointerPropertyRNA rna_ID_user_of_id_id;
extern IntPropertyRNA rna_ID_user_of_id_count;

extern FunctionRNA rna_ID_animation_data_create_func;
extern PointerPropertyRNA rna_ID_animation_data_create_anim_data;

extern FunctionRNA rna_ID_animation_data_clear_func;
extern FunctionRNA rna_ID_update_tag_func;
extern EnumPropertyRNA rna_ID_update_tag_refresh;


extern FunctionRNA rna_Camera_view_frame_func;
extern PointerPropertyRNA rna_Camera_view_frame_scene;
extern FloatPropertyRNA rna_Camera_view_frame_result_1;
extern FloatPropertyRNA rna_Camera_view_frame_result_2;
extern FloatPropertyRNA rna_Camera_view_frame_result_3;
extern FloatPropertyRNA rna_Camera_view_frame_result_4;



CollectionPropertyRNA rna_CameraStereoData_rna_properties;
PointerPropertyRNA rna_CameraStereoData_rna_type;
EnumPropertyRNA rna_CameraStereoData_convergence_mode;
EnumPropertyRNA rna_CameraStereoData_pivot;
FloatPropertyRNA rna_CameraStereoData_interocular_distance;
FloatPropertyRNA rna_CameraStereoData_convergence_distance;
BoolPropertyRNA rna_CameraStereoData_use_spherical_stereo;
BoolPropertyRNA rna_CameraStereoData_use_pole_merge;
FloatPropertyRNA rna_CameraStereoData_pole_merge_angle_from;
FloatPropertyRNA rna_CameraStereoData_pole_merge_angle_to;


CollectionPropertyRNA rna_GameCameraViewportData_rna_properties;
PointerPropertyRNA rna_GameCameraViewportData_rna_type;
FloatPropertyRNA rna_GameCameraViewportData_left_ratio;
FloatPropertyRNA rna_GameCameraViewportData_right_ratio;
FloatPropertyRNA rna_GameCameraViewportData_bottom_ratio;
FloatPropertyRNA rna_GameCameraViewportData_top_ratio;

int Camera_type_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (int)(data->type);
}

void Camera_type_set(PointerRNA *ptr, int value)
{
	Camera *data = (Camera *)(ptr->data);
	data->type = value;
}

int Camera_show_guide_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (int)(data->dtx);
}

void Camera_show_guide_set(PointerRNA *ptr, int value)
{
	Camera *data = (Camera *)(ptr->data);
	data->dtx = value;
}

int Camera_sensor_fit_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (int)(data->sensor_fit);
}

void Camera_sensor_fit_set(PointerRNA *ptr, int value)
{
	Camera *data = (Camera *)(ptr->data);
	data->sensor_fit = value;
}

float Camera_passepartout_alpha_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (float)(data->passepartalpha);
}

void Camera_passepartout_alpha_set(PointerRNA *ptr, float value)
{
	Camera *data = (Camera *)(ptr->data);
	data->passepartalpha = CLAMPIS(value, 0.0f, 1.0f);
}

float Camera_angle_x_get(PointerRNA *ptr)
{
	return rna_Camera_angle_x_get(ptr);
}

void Camera_angle_x_set(PointerRNA *ptr, float value)
{
	rna_Camera_angle_x_set(ptr, value);
}

float Camera_angle_y_get(PointerRNA *ptr)
{
	return rna_Camera_angle_y_get(ptr);
}

void Camera_angle_y_set(PointerRNA *ptr, float value)
{
	rna_Camera_angle_y_set(ptr, value);
}

float Camera_angle_get(PointerRNA *ptr)
{
	return rna_Camera_angle_get(ptr);
}

void Camera_angle_set(PointerRNA *ptr, float value)
{
	rna_Camera_angle_set(ptr, value);
}

float Camera_clip_start_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (float)(data->clipsta);
}

void Camera_clip_start_set(PointerRNA *ptr, float value)
{
	Camera *data = (Camera *)(ptr->data);
	data->clipsta = CLAMPIS(value, 0.0000010000f, FLT_MAX);
}

float Camera_clip_end_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (float)(data->clipend);
}

void Camera_clip_end_set(PointerRNA *ptr, float value)
{
	Camera *data = (Camera *)(ptr->data);
	data->clipend = CLAMPIS(value, 0.0000010000f, FLT_MAX);
}

float Camera_lens_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (float)(data->lens);
}

void Camera_lens_set(PointerRNA *ptr, float value)
{
	Camera *data = (Camera *)(ptr->data);
	data->lens = CLAMPIS(value, 1.0f, FLT_MAX);
}

float Camera_sensor_width_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (float)(data->sensor_x);
}

void Camera_sensor_width_set(PointerRNA *ptr, float value)
{
	Camera *data = (Camera *)(ptr->data);
	data->sensor_x = CLAMPIS(value, 1.0f, FLT_MAX);
}

float Camera_sensor_height_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (float)(data->sensor_y);
}

void Camera_sensor_height_set(PointerRNA *ptr, float value)
{
	Camera *data = (Camera *)(ptr->data);
	data->sensor_y = CLAMPIS(value, 1.0f, FLT_MAX);
}

float Camera_ortho_scale_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (float)(data->ortho_scale);
}

void Camera_ortho_scale_set(PointerRNA *ptr, float value)
{
	Camera *data = (Camera *)(ptr->data);
	data->ortho_scale = CLAMPIS(value, 0.0000000000f, FLT_MAX);
}

float Camera_draw_size_get(PointerRNA *ptr)
{
	return rna_Camera_draw_size_get(ptr);
}

void Camera_draw_size_set(PointerRNA *ptr, float value)
{
	rna_Camera_draw_size_set(ptr, value);
}

float Camera_shift_x_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (float)(data->shiftx);
}

void Camera_shift_x_set(PointerRNA *ptr, float value)
{
	Camera *data = (Camera *)(ptr->data);
	data->shiftx = CLAMPIS(value, -10.0f, 10.0f);
}

float Camera_shift_y_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (float)(data->shifty);
}

void Camera_shift_y_set(PointerRNA *ptr, float value)
{
	Camera *data = (Camera *)(ptr->data);
	data->shifty = CLAMPIS(value, -10.0f, 10.0f);
}

float Camera_dof_distance_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (float)(data->YF_dofdist);
}

void Camera_dof_distance_set(PointerRNA *ptr, float value)
{
	Camera *data = (Camera *)(ptr->data);
	data->YF_dofdist = CLAMPIS(value, 0.0f, FLT_MAX);
}

float Camera_lod_factor_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (float)(data->lodfactor);
}

void Camera_lod_factor_set(PointerRNA *ptr, float value)
{
	Camera *data = (Camera *)(ptr->data);
	data->lodfactor = CLAMPIS(value, 0.0f, FLT_MAX);
}

PointerRNA Camera_stereo_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return rna_pointer_inherit_refine(ptr, &RNA_CameraStereoData, &data->stereo);
}

PointerRNA Camera_viewport_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return rna_pointer_inherit_refine(ptr, &RNA_GameCameraViewportData, &data->gameviewport);
}

bool Camera_override_culling_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (((data->gameflag) & 2) != 0);
}

void Camera_override_culling_set(PointerRNA *ptr, bool value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value) data->gameflag |= 2;
	else data->gameflag &= ~2;
}

bool Camera_show_frustum_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (((data->gameflag) & 1) != 0);
}

void Camera_show_frustum_set(PointerRNA *ptr, bool value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value) data->gameflag |= 1;
	else data->gameflag &= ~1;
}

bool Camera_use_viewport_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (((data->gameflag) & 8) != 0);
}

void Camera_use_viewport_set(PointerRNA *ptr, bool value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value) data->gameflag |= 8;
	else data->gameflag &= ~8;
}

bool Camera_use_object_activity_culling_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (((data->gameflag) & 4) != 0);
}

void Camera_use_object_activity_culling_set(PointerRNA *ptr, bool value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value) data->gameflag |= 4;
	else data->gameflag &= ~4;
}

bool Camera_show_limits_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (((data->flag) & 1) != 0);
}

void Camera_show_limits_set(PointerRNA *ptr, bool value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value) data->flag |= 1;
	else data->flag &= ~1;
}

bool Camera_show_mist_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (((data->flag) & 2) != 0);
}

void Camera_show_mist_set(PointerRNA *ptr, bool value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value) data->flag |= 2;
	else data->flag &= ~2;
}

bool Camera_show_passepartout_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (((data->flag) & 4) != 0);
}

void Camera_show_passepartout_set(PointerRNA *ptr, bool value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value) data->flag |= 4;
	else data->flag &= ~4;
}

bool Camera_show_safe_areas_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (((data->flag) & 8) != 0);
}

void Camera_show_safe_areas_set(PointerRNA *ptr, bool value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value) data->flag |= 8;
	else data->flag &= ~8;
}

bool Camera_show_safe_center_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (((data->flag) & 512) != 0);
}

void Camera_show_safe_center_set(PointerRNA *ptr, bool value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value) data->flag |= 512;
	else data->flag &= ~512;
}

bool Camera_show_name_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (((data->flag) & 16) != 0);
}

void Camera_show_name_set(PointerRNA *ptr, bool value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value) data->flag |= 16;
	else data->flag &= ~16;
}

bool Camera_show_sensor_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return (((data->flag) & 256) != 0);
}

void Camera_show_sensor_set(PointerRNA *ptr, bool value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value) data->flag |= 256;
	else data->flag &= ~256;
}

int Camera_lens_unit_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return ((data->flag) & 32);
}

void Camera_lens_unit_set(PointerRNA *ptr, int value)
{
	Camera *data = (Camera *)(ptr->data);
	data->flag &= ~32;
	data->flag |= value;
}

PointerRNA Camera_dof_object_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return rna_pointer_inherit_refine(ptr, &RNA_Object, data->dof_ob);
}

void Camera_dof_object_set(PointerRNA *ptr, PointerRNA value)
{
	Camera *data = (Camera *)(ptr->data);
	if (value.data)
		id_lib_extern((ID *)value.data);

	data->dof_ob = value.data;
}

PointerRNA Camera_gpu_dof_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return rna_pointer_inherit_refine(ptr, &RNA_GPUDOFSettings, &data->gpu_dof);
}

PointerRNA Camera_animation_data_get(PointerRNA *ptr)
{
	Camera *data = (Camera *)(ptr->data);
	return rna_pointer_inherit_refine(ptr, &RNA_AnimData, data->adt);
}

static PointerRNA CameraStereoData_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void CameraStereoData_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_CameraStereoData_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = CameraStereoData_rna_properties_get(iter);
}

void CameraStereoData_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = CameraStereoData_rna_properties_get(iter);
}

void CameraStereoData_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int CameraStereoData_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA CameraStereoData_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

int CameraStereoData_convergence_mode_get(PointerRNA *ptr)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	return (int)(data->convergence_mode);
}

void CameraStereoData_convergence_mode_set(PointerRNA *ptr, int value)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	data->convergence_mode = value;
}

int CameraStereoData_pivot_get(PointerRNA *ptr)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	return (int)(data->pivot);
}

void CameraStereoData_pivot_set(PointerRNA *ptr, int value)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	data->pivot = value;
}

float CameraStereoData_interocular_distance_get(PointerRNA *ptr)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	return (float)(data->interocular_distance);
}

void CameraStereoData_interocular_distance_set(PointerRNA *ptr, float value)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	data->interocular_distance = CLAMPIS(value, 0.0f, FLT_MAX);
}

float CameraStereoData_convergence_distance_get(PointerRNA *ptr)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	return (float)(data->convergence_distance);
}

void CameraStereoData_convergence_distance_set(PointerRNA *ptr, float value)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	data->convergence_distance = CLAMPIS(value, 0.0000100000f, FLT_MAX);
}

bool CameraStereoData_use_spherical_stereo_get(PointerRNA *ptr)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	return (((data->flag) & 1) != 0);
}

void CameraStereoData_use_spherical_stereo_set(PointerRNA *ptr, bool value)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	if (value) data->flag |= 1;
	else data->flag &= ~1;
}

bool CameraStereoData_use_pole_merge_get(PointerRNA *ptr)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	return (((data->flag) & 2) != 0);
}

void CameraStereoData_use_pole_merge_set(PointerRNA *ptr, bool value)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	if (value) data->flag |= 2;
	else data->flag &= ~2;
}

float CameraStereoData_pole_merge_angle_from_get(PointerRNA *ptr)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	return (float)(data->pole_merge_angle_from);
}

void CameraStereoData_pole_merge_angle_from_set(PointerRNA *ptr, float value)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	data->pole_merge_angle_from = CLAMPIS(value, 0.0f, 1.5707963705f);
}

float CameraStereoData_pole_merge_angle_to_get(PointerRNA *ptr)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	return (float)(data->pole_merge_angle_to);
}

void CameraStereoData_pole_merge_angle_to_set(PointerRNA *ptr, float value)
{
	CameraStereoSettings *data = (CameraStereoSettings *)(ptr->data);
	data->pole_merge_angle_to = CLAMPIS(value, 0.0f, 1.5707963705f);
}

static PointerRNA GameCameraViewportData_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void GameCameraViewportData_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GameCameraViewportData_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = GameCameraViewportData_rna_properties_get(iter);
}

void GameCameraViewportData_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = GameCameraViewportData_rna_properties_get(iter);
}

void GameCameraViewportData_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GameCameraViewportData_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA GameCameraViewportData_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

float GameCameraViewportData_left_ratio_get(PointerRNA *ptr)
{
	GameCameraViewportSettings *data = (GameCameraViewportSettings *)(ptr->data);
	return (float)(data->leftratio);
}

void GameCameraViewportData_left_ratio_set(PointerRNA *ptr, float value)
{
	GameCameraViewportSettings *data = (GameCameraViewportSettings *)(ptr->data);
	data->leftratio = CLAMPIS(value, 0.0f, 1.0f);
}

float GameCameraViewportData_right_ratio_get(PointerRNA *ptr)
{
	GameCameraViewportSettings *data = (GameCameraViewportSettings *)(ptr->data);
	return (float)(data->rightratio);
}

void GameCameraViewportData_right_ratio_set(PointerRNA *ptr, float value)
{
	GameCameraViewportSettings *data = (GameCameraViewportSettings *)(ptr->data);
	data->rightratio = CLAMPIS(value, 0.0f, 1.0f);
}

float GameCameraViewportData_bottom_ratio_get(PointerRNA *ptr)
{
	GameCameraViewportSettings *data = (GameCameraViewportSettings *)(ptr->data);
	return (float)(data->bottomratio);
}

void GameCameraViewportData_bottom_ratio_set(PointerRNA *ptr, float value)
{
	GameCameraViewportSettings *data = (GameCameraViewportSettings *)(ptr->data);
	data->bottomratio = CLAMPIS(value, 0.0f, 1.0f);
}

float GameCameraViewportData_top_ratio_get(PointerRNA *ptr)
{
	GameCameraViewportSettings *data = (GameCameraViewportSettings *)(ptr->data);
	return (float)(data->topratio);
}

void GameCameraViewportData_top_ratio_set(PointerRNA *ptr, float value)
{
	GameCameraViewportSettings *data = (GameCameraViewportSettings *)(ptr->data);
	data->topratio = CLAMPIS(value, 0.0f, 1.0f);
}

void Camera_view_frame(struct Camera *_self, struct Scene *scene, float result_1[3], float result_2[3], float result_3[3], float result_4[3])
{
	rna_camera_view_frame(_self, scene, result_1, result_2, result_3, result_4);
}

void Camera_view_frame_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct Camera *_self;
	struct Scene *scene;
	float *result_1;
	float *result_2;
	float *result_3;
	float *result_4;
	char *_data;
	
	_self = (struct Camera *)_ptr->data;
	_data = (char *)_parms->data;
	scene = *((struct Scene **)_data);
	_data += 8;
	result_1 = ((float *)_data);
	_data += 12;
	result_2 = ((float *)_data);
	_data += 12;
	result_3 = ((float *)_data);
	_data += 12;
	result_4 = ((float *)_data);
	
	rna_camera_view_frame(_self, scene, result_1, result_2, result_3, result_4);
}

/* Repeated prototypes to detect errors */

void rna_camera_view_frame(struct Camera *_self, struct Scene *scene, float result_1[3], float result_2[3], float result_3[3], float result_4[3]);



/* Camera */
static const EnumPropertyItem rna_Camera_type_items[4] = {
	{0, "PERSP", 0, "Perspective", ""},
	{1, "ORTHO", 0, "Orthographic", ""},
	{2, "PANO", 0, "Panoramic", ""},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_Camera_type = {
	{(PropertyRNA *)&rna_Camera_show_guide, NULL,
	-1, "type", 3, 0, 0, 0, "Type",
	"Camera types",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_update, 85393408, NULL, NULL,
	0, -1, NULL},
	Camera_type_get, Camera_type_set, NULL, NULL, NULL, NULL, rna_Camera_type_items, 3, 0
};

static const EnumPropertyItem rna_Camera_show_guide_items[9] = {
	{1, "CENTER", 0, "Center", ""},
	{2, "CENTER_DIAGONAL", 0, "Center Diagonal", ""},
	{4, "THIRDS", 0, "Thirds", ""},
	{8, "GOLDEN", 0, "Golden", ""},
	{16, "GOLDEN_TRIANGLE_A", 0, "Golden Triangle A", ""},
	{32, "GOLDEN_TRIANGLE_B", 0, "Golden Triangle B", ""},
	{64, "HARMONY_TRIANGLE_A", 0, "Harmonious Triangle A", ""},
	{128, "HARMONY_TRIANGLE_B", 0, "Harmonious Triangle B", ""},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_Camera_show_guide = {
	{(PropertyRNA *)&rna_Camera_sensor_fit, (PropertyRNA *)&rna_Camera_type,
	-1, "show_guide", 2097155, 0, 0, 0, "Composition Guides",
	"Draw overlay",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 404684800, NULL, NULL,
	0, -1, NULL},
	Camera_show_guide_get, Camera_show_guide_set, NULL, NULL, NULL, NULL, rna_Camera_show_guide_items, 8, 1
};

static const EnumPropertyItem rna_Camera_sensor_fit_items[4] = {
	{0, "AUTO", 0, "Auto", "Fit to the sensor width or height depending on image resolution"},
	{1, "HORIZONTAL", 0, "Horizontal", "Fit to the sensor width"},
	{2, "VERTICAL", 0, "Vertical", "Fit to the sensor height"},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_Camera_sensor_fit = {
	{(PropertyRNA *)&rna_Camera_passepartout_alpha, (PropertyRNA *)&rna_Camera_show_guide,
	-1, "sensor_fit", 3, 0, 0, 0, "Sensor Fit",
	"Method to fit image and field of view angle inside the sensor",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_update, 85393408, NULL, NULL,
	0, -1, NULL},
	Camera_sensor_fit_get, Camera_sensor_fit_set, NULL, NULL, NULL, NULL, rna_Camera_sensor_fit_items, 3, 0
};

FloatPropertyRNA rna_Camera_passepartout_alpha = {
	{(PropertyRNA *)&rna_Camera_angle_x, (PropertyRNA *)&rna_Camera_sensor_fit,
	-1, "passepartout_alpha", 3, 0, 4, 0, "Passepartout Alpha",
	"Opacity (alpha) of the darkened overlay in Camera view",
	0, "*",
	PROP_FLOAT, PROP_FACTOR | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 404684800, NULL, NULL,
	offsetof(Camera, passepartalpha), 5, NULL},
	Camera_passepartout_alpha_get, Camera_passepartout_alpha_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_angle_x = {
	{(PropertyRNA *)&rna_Camera_angle_y, (PropertyRNA *)&rna_Camera_passepartout_alpha,
	-1, "angle_x", 1, 0, 0, 0, "Horizontal FOV",
	"Camera lens horizontal field of view",
	0, "*",
	PROP_FLOAT, PROP_ANGLE | PROP_UNIT_ROTATION, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_update, 85393408, NULL, NULL,
	0, -1, NULL},
	Camera_angle_x_get, Camera_angle_x_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0064053582f, 3.0167491436f, 0.0064053582f, 3.0167491436f, 10.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_angle_y = {
	{(PropertyRNA *)&rna_Camera_angle, (PropertyRNA *)&rna_Camera_angle_x,
	-1, "angle_y", 1, 0, 0, 0, "Vertical FOV",
	"Camera lens vertical field of view",
	0, "*",
	PROP_FLOAT, PROP_ANGLE | PROP_UNIT_ROTATION, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_update, 85393408, NULL, NULL,
	0, -1, NULL},
	Camera_angle_y_get, Camera_angle_y_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0064053582f, 3.0167491436f, 0.0064053582f, 3.0167491436f, 10.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_angle = {
	{(PropertyRNA *)&rna_Camera_clip_start, (PropertyRNA *)&rna_Camera_angle_y,
	-1, "angle", 1, 0, 0, 0, "Field of View",
	"Camera lens field of view",
	0, "*",
	PROP_FLOAT, PROP_ANGLE | PROP_UNIT_ROTATION, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_update, 85393408, NULL, NULL,
	0, -1, NULL},
	Camera_angle_get, Camera_angle_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0064053582f, 3.0167491436f, 0.0064053582f, 3.0167491436f, 10.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_clip_start = {
	{(PropertyRNA *)&rna_Camera_clip_end, (PropertyRNA *)&rna_Camera_angle,
	-1, "clip_start", 3, 0, 4, 0, "Clip Start",
	"Camera near clipping distance",
	0, "*",
	PROP_FLOAT, PROP_DISTANCE | PROP_UNIT_LENGTH, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	offsetof(Camera, clipsta), 5, NULL},
	Camera_clip_start_get, Camera_clip_start_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0010000000f, FLT_MAX, 0.0000010000f, FLT_MAX, 10.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_clip_end = {
	{(PropertyRNA *)&rna_Camera_lens, (PropertyRNA *)&rna_Camera_clip_start,
	-1, "clip_end", 3, 0, 4, 0, "Clip End",
	"Camera far clipping distance",
	0, "*",
	PROP_FLOAT, PROP_DISTANCE | PROP_UNIT_LENGTH, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	offsetof(Camera, clipend), 5, NULL},
	Camera_clip_end_get, Camera_clip_end_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0010000000f, FLT_MAX, 0.0000010000f, FLT_MAX, 10.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_lens = {
	{(PropertyRNA *)&rna_Camera_sensor_width, (PropertyRNA *)&rna_Camera_clip_end,
	-1, "lens", 3, 0, 4, 0, "Focal Length",
	"Perspective Camera lens value in millimeters",
	0, "*",
	PROP_FLOAT, PROP_DISTANCE_CAMERA | PROP_UNIT_CAMERA, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_update, 85393408, NULL, NULL,
	offsetof(Camera, lens), 5, NULL},
	Camera_lens_get, Camera_lens_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0f, 5000.0f, 1.0f, FLT_MAX, 1.0f, 2, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_sensor_width = {
	{(PropertyRNA *)&rna_Camera_sensor_height, (PropertyRNA *)&rna_Camera_lens,
	-1, "sensor_width", 3, 0, 4, 0, "Sensor Width",
	"Horizontal size of the image sensor area in millimeters",
	0, "*",
	PROP_FLOAT, PROP_DISTANCE_CAMERA | PROP_UNIT_CAMERA, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_update, 85393408, NULL, NULL,
	offsetof(Camera, sensor_x), 5, NULL},
	Camera_sensor_width_get, Camera_sensor_width_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0f, 100.0f, 1.0f, FLT_MAX, 1.0f, 2, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_sensor_height = {
	{(PropertyRNA *)&rna_Camera_ortho_scale, (PropertyRNA *)&rna_Camera_sensor_width,
	-1, "sensor_height", 3, 0, 4, 0, "Sensor Height",
	"Vertical size of the image sensor area in millimeters",
	0, "*",
	PROP_FLOAT, PROP_DISTANCE_CAMERA | PROP_UNIT_CAMERA, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_update, 85393408, NULL, NULL,
	offsetof(Camera, sensor_y), 5, NULL},
	Camera_sensor_height_get, Camera_sensor_height_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0f, 100.0f, 1.0f, FLT_MAX, 1.0f, 2, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_ortho_scale = {
	{(PropertyRNA *)&rna_Camera_draw_size, (PropertyRNA *)&rna_Camera_sensor_height,
	-1, "ortho_scale", 3, 0, 4, 0, "Orthographic Scale",
	"Orthographic Camera scale (similar to zoom)",
	0, "*",
	PROP_FLOAT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_update, 85393408, NULL, NULL,
	offsetof(Camera, ortho_scale), 5, NULL},
	Camera_ortho_scale_get, Camera_ortho_scale_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0010000000f, 10000.0f, 0.0000000000f, FLT_MAX, 10.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_draw_size = {
	{(PropertyRNA *)&rna_Camera_shift_x, (PropertyRNA *)&rna_Camera_ortho_scale,
	-1, "draw_size", 3, 0, 0, 0, "Draw Size",
	"Apparent size of the Camera object in the 3D View",
	0, "*",
	PROP_FLOAT, PROP_DISTANCE | PROP_UNIT_LENGTH, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	0, -1, NULL},
	Camera_draw_size_get, Camera_draw_size_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0099999998f, 100.0f, 0.0099999998f, 1000.0f, 1.0f, 2, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_shift_x = {
	{(PropertyRNA *)&rna_Camera_shift_y, (PropertyRNA *)&rna_Camera_draw_size,
	-1, "shift_x", 3, 0, 4, 0, "Shift X",
	"Camera horizontal shift",
	0, "*",
	PROP_FLOAT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_update, 85393408, NULL, NULL,
	offsetof(Camera, shiftx), 5, NULL},
	Camera_shift_x_get, Camera_shift_x_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -2.0f, 2.0f, -10.0f, 10.0f, 1.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_shift_y = {
	{(PropertyRNA *)&rna_Camera_dof_distance, (PropertyRNA *)&rna_Camera_shift_x,
	-1, "shift_y", 3, 0, 4, 0, "Shift Y",
	"Camera vertical shift",
	0, "*",
	PROP_FLOAT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_update, 85393408, NULL, NULL,
	offsetof(Camera, shifty), 5, NULL},
	Camera_shift_y_get, Camera_shift_y_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -2.0f, 2.0f, -10.0f, 10.0f, 1.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_dof_distance = {
	{(PropertyRNA *)&rna_Camera_lod_factor, (PropertyRNA *)&rna_Camera_shift_y,
	-1, "dof_distance", 3, 0, 4, 0, "DOF Distance",
	"Distance to the focus point for depth of field",
	0, "*",
	PROP_FLOAT, PROP_DISTANCE | PROP_UNIT_LENGTH, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_dof_update, 85393408, NULL, NULL,
	offsetof(Camera, YF_dofdist), 5, NULL},
	Camera_dof_distance_get, Camera_dof_distance_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 5000.0f, 0.0f, FLT_MAX, 1.0f, 2, 0.0f, NULL
};

FloatPropertyRNA rna_Camera_lod_factor = {
	{(PropertyRNA *)&rna_Camera_stereo, (PropertyRNA *)&rna_Camera_dof_distance,
	-1, "lod_factor", 3, 0, 4, 0, "Level of Detail Distance Factor",
	"The factor applied to distance computed in Lod",
	0, "*",
	PROP_FLOAT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 85852160, NULL, NULL,
	offsetof(Camera, lodfactor), 5, NULL},
	Camera_lod_factor_get, Camera_lod_factor_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, FLT_MAX, 0.0f, FLT_MAX, 10.0f, 3, 1.0f, NULL
};

PointerPropertyRNA rna_Camera_stereo = {
	{(PropertyRNA *)&rna_Camera_viewport, (PropertyRNA *)&rna_Camera_lod_factor,
	-1, "stereo", 8650752, 0, 0, 0, "Stereo",
	"",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	Camera_stereo_get, NULL, NULL, NULL,&RNA_CameraStereoData
};

PointerPropertyRNA rna_Camera_viewport = {
	{(PropertyRNA *)&rna_Camera_override_culling, (PropertyRNA *)&rna_Camera_stereo,
	-1, "viewport", 8650752, 0, 0, 0, "viewport",
	"",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	Camera_viewport_get, NULL, NULL, NULL,&RNA_GameCameraViewportData
};

BoolPropertyRNA rna_Camera_override_culling = {
	{(PropertyRNA *)&rna_Camera_show_frustum, (PropertyRNA *)&rna_Camera_viewport,
	-1, "override_culling", 3, 0, 0, 0, "Override Culling",
	"Use only this camera for scene culling in Game Engine",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 402653184, NULL, NULL,
	0, -1, NULL},
	Camera_override_culling_get, Camera_override_culling_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Camera_show_frustum = {
	{(PropertyRNA *)&rna_Camera_use_viewport, (PropertyRNA *)&rna_Camera_override_culling,
	-1, "show_frustum", 3, 0, 0, 0, "Show Frustum",
	"Show a visualization of frustum in Game Engine",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 402653184, NULL, NULL,
	0, -1, NULL},
	Camera_show_frustum_get, Camera_show_frustum_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Camera_use_viewport = {
	{(PropertyRNA *)&rna_Camera_use_object_activity_culling, (PropertyRNA *)&rna_Camera_show_frustum,
	-1, "use_viewport", 3, 0, 0, 0, "Show Frustum",
	"Show a visualization of frustum in Game Engine",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 402653184, NULL, NULL,
	0, -1, NULL},
	Camera_use_viewport_get, Camera_use_viewport_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Camera_use_object_activity_culling = {
	{(PropertyRNA *)&rna_Camera_show_limits, (PropertyRNA *)&rna_Camera_use_viewport,
	-1, "use_object_activity_culling", 3, 0, 0, 0, "Activity Culling",
	"Enable object activity culling with this camera",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	Camera_use_object_activity_culling_get, Camera_use_object_activity_culling_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Camera_show_limits = {
	{(PropertyRNA *)&rna_Camera_show_mist, (PropertyRNA *)&rna_Camera_use_object_activity_culling,
	-1, "show_limits", 3, 0, 0, 0, "Show Limits",
	"Draw the clipping range and focus point on the camera",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	0, -1, NULL},
	Camera_show_limits_get, Camera_show_limits_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Camera_show_mist = {
	{(PropertyRNA *)&rna_Camera_show_passepartout, (PropertyRNA *)&rna_Camera_show_limits,
	-1, "show_mist", 3, 0, 0, 0, "Show Mist",
	"Draw a line from the Camera to indicate the mist area",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	0, -1, NULL},
	Camera_show_mist_get, Camera_show_mist_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Camera_show_passepartout = {
	{(PropertyRNA *)&rna_Camera_show_safe_areas, (PropertyRNA *)&rna_Camera_show_mist,
	-1, "show_passepartout", 3, 0, 0, 0, "Show Passepartout",
	"Show a darkened overlay outside the image area in Camera view",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 404684800, NULL, NULL,
	0, -1, NULL},
	Camera_show_passepartout_get, Camera_show_passepartout_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Camera_show_safe_areas = {
	{(PropertyRNA *)&rna_Camera_show_safe_center, (PropertyRNA *)&rna_Camera_show_passepartout,
	-1, "show_safe_areas", 3, 0, 0, 0, "Show Safe Areas",
	"Show TV title safe and action safe areas in Camera view",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 404684800, NULL, NULL,
	0, -1, NULL},
	Camera_show_safe_areas_get, Camera_show_safe_areas_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Camera_show_safe_center = {
	{(PropertyRNA *)&rna_Camera_show_name, (PropertyRNA *)&rna_Camera_show_safe_areas,
	-1, "show_safe_center", 3, 0, 0, 0, "Show Center-cut safe areas",
	"Show safe areas to fit content in a different aspect ratio",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 404684800, NULL, NULL,
	0, -1, NULL},
	Camera_show_safe_center_get, Camera_show_safe_center_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Camera_show_name = {
	{(PropertyRNA *)&rna_Camera_show_sensor, (PropertyRNA *)&rna_Camera_show_safe_center,
	-1, "show_name", 3, 0, 0, 0, "Show Name",
	"Show the active Camera\'s name in Camera view",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 404684800, NULL, NULL,
	0, -1, NULL},
	Camera_show_name_get, Camera_show_name_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Camera_show_sensor = {
	{(PropertyRNA *)&rna_Camera_lens_unit, (PropertyRNA *)&rna_Camera_show_name,
	-1, "show_sensor", 3, 0, 0, 0, "Show Sensor Size",
	"Show sensor size (film gate) in Camera view",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 404684800, NULL, NULL,
	0, -1, NULL},
	Camera_show_sensor_get, Camera_show_sensor_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

static const EnumPropertyItem rna_Camera_lens_unit_items[3] = {
	{0, "MILLIMETERS", 0, "Millimeters", "Specify the lens in millimeters"},
	{32, "FOV", 0, "Field of View", "Specify the lens as the field of view\'s angle"},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_Camera_lens_unit = {
	{(PropertyRNA *)&rna_Camera_dof_object, (PropertyRNA *)&rna_Camera_show_sensor,
	-1, "lens_unit", 3, 0, 0, 0, "Lens Unit",
	"Unit to edit lens in for the user interface",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	Camera_lens_unit_get, Camera_lens_unit_set, NULL, NULL, NULL, NULL, rna_Camera_lens_unit_items, 2, 0
};

PointerPropertyRNA rna_Camera_dof_object = {
	{(PropertyRNA *)&rna_Camera_gpu_dof, (PropertyRNA *)&rna_Camera_lens_unit,
	-1, "dof_object", 8388609, 0, 0, 0, "DOF Object",
	"Use this object to define the depth of field focal point",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_Camera_dependency_update, 85393408, NULL, NULL,
	0, -1, NULL},
	Camera_dof_object_get, Camera_dof_object_set, NULL, NULL,&RNA_Object
};

PointerPropertyRNA rna_Camera_gpu_dof = {
	{(PropertyRNA *)&rna_Camera_animation_data, (PropertyRNA *)&rna_Camera_dof_object,
	-1, "gpu_dof", 8388608, 0, 0, 0, "GPU Depth Of Field",
	"",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	0, -1, NULL},
	Camera_gpu_dof_get, NULL, NULL, NULL,&RNA_GPUDOFSettings
};

PointerPropertyRNA rna_Camera_animation_data = {
	{NULL, (PropertyRNA *)&rna_Camera_gpu_dof,
	-1, "animation_data", 8388608, 0, 0, 0, "Animation Data",
	"Animation data for this data-block",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	Camera_animation_data_get, NULL, NULL, NULL,&RNA_AnimData
};

PointerPropertyRNA rna_Camera_view_frame_scene = {
	{(PropertyRNA *)&rna_Camera_view_frame_result_1, NULL,
	-1, "scene", 8388608, 0, 0, 0, "",
	"Scene to use for aspect calculation, when omitted 1:1 aspect is used",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_Scene
};

static float rna_Camera_view_frame_result_1_default[3] = {
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_Camera_view_frame_result_1 = {
	{(PropertyRNA *)&rna_Camera_view_frame_result_2, (PropertyRNA *)&rna_Camera_view_frame_scene,
	-1, "result_1", 8388611, 2, 0, 0, "Result",
	NULL,
	0, "*",
	PROP_FLOAT, PROP_XYZ | PROP_UNIT_NONE, NULL, 1, {3, 0, 0}, 3,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 1.0f, 3, 0.0f, rna_Camera_view_frame_result_1_default
};

static float rna_Camera_view_frame_result_2_default[3] = {
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_Camera_view_frame_result_2 = {
	{(PropertyRNA *)&rna_Camera_view_frame_result_3, (PropertyRNA *)&rna_Camera_view_frame_result_1,
	-1, "result_2", 8388611, 2, 0, 0, "Result",
	NULL,
	0, "*",
	PROP_FLOAT, PROP_XYZ | PROP_UNIT_NONE, NULL, 1, {3, 0, 0}, 3,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 1.0f, 3, 0.0f, rna_Camera_view_frame_result_2_default
};

static float rna_Camera_view_frame_result_3_default[3] = {
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_Camera_view_frame_result_3 = {
	{(PropertyRNA *)&rna_Camera_view_frame_result_4, (PropertyRNA *)&rna_Camera_view_frame_result_2,
	-1, "result_3", 8388611, 2, 0, 0, "Result",
	NULL,
	0, "*",
	PROP_FLOAT, PROP_XYZ | PROP_UNIT_NONE, NULL, 1, {3, 0, 0}, 3,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 1.0f, 3, 0.0f, rna_Camera_view_frame_result_3_default
};

static float rna_Camera_view_frame_result_4_default[3] = {
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_Camera_view_frame_result_4 = {
	{NULL, (PropertyRNA *)&rna_Camera_view_frame_result_3,
	-1, "result_4", 8388611, 2, 0, 0, "Result",
	NULL,
	0, "*",
	PROP_FLOAT, PROP_XYZ | PROP_UNIT_NONE, NULL, 1, {3, 0, 0}, 3,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 1.0f, 3, 0.0f, rna_Camera_view_frame_result_4_default
};

FunctionRNA rna_Camera_view_frame_func = {
	{NULL, NULL,
	NULL,
	{(PropertyRNA *)&rna_Camera_view_frame_scene, (PropertyRNA *)&rna_Camera_view_frame_result_4}},
	"view_frame", 0, "Return 4 points for the cameras frame (before object transformation)",
	Camera_view_frame_call,
	NULL
};

StructRNA RNA_Camera = {
	{(ContainerRNA *)&RNA_CameraStereoData, (ContainerRNA *)&RNA_AlembicObjectPath,
	NULL,
	{(PropertyRNA *)&rna_Camera_type, (PropertyRNA *)&rna_Camera_animation_data}},
	"Camera", NULL, NULL, 519, NULL, "Camera",
	"Camera data-block for storing camera settings",
	"*", 168,
	(PropertyRNA *)&rna_ID_name, (PropertyRNA *)&rna_ID_rna_properties,
	&RNA_ID,
	NULL,
	rna_ID_refine,
	NULL,
	NULL,
	NULL,
	rna_ID_instance,
	rna_ID_idprops,
	{(FunctionRNA *)&rna_Camera_view_frame_func, (FunctionRNA *)&rna_Camera_view_frame_func}
};

/* Stereo */
CollectionPropertyRNA rna_CameraStereoData_rna_properties = {
	{(PropertyRNA *)&rna_CameraStereoData_rna_type, NULL,
	-1, "rna_properties", 0, 0, 1, 0, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	CameraStereoData_rna_properties_begin, CameraStereoData_rna_properties_next, CameraStereoData_rna_properties_end, CameraStereoData_rna_properties_get, NULL, NULL, CameraStereoData_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_CameraStereoData_rna_type = {
	{(PropertyRNA *)&rna_CameraStereoData_convergence_mode, (PropertyRNA *)&rna_CameraStereoData_rna_properties,
	-1, "rna_type", 8912896, 0, 0, 0, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	CameraStereoData_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

static const EnumPropertyItem rna_CameraStereoData_convergence_mode_items[4] = {
	{0, "OFFAXIS", 0, "Off-Axis", "Off-axis frustums converging in a plane"},
	{1, "PARALLEL", 0, "Parallel", "Parallel cameras with no convergence"},
	{2, "TOE", 0, "Toe-in", "Rotated cameras, looking at the convergence distance"},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_CameraStereoData_convergence_mode = {
	{(PropertyRNA *)&rna_CameraStereoData_pivot, (PropertyRNA *)&rna_CameraStereoData_rna_type,
	-1, "convergence_mode", 3, 0, 0, 0, "Mode",
	"",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	0, -1, NULL},
	CameraStereoData_convergence_mode_get, CameraStereoData_convergence_mode_set, NULL, NULL, NULL, NULL, rna_CameraStereoData_convergence_mode_items, 3, 0
};

static const EnumPropertyItem rna_CameraStereoData_pivot_items[4] = {
	{0, "LEFT", 0, "Left", ""},
	{1, "RIGHT", 0, "Right", ""},
	{2, "CENTER", 0, "Center", ""},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_CameraStereoData_pivot = {
	{(PropertyRNA *)&rna_CameraStereoData_interocular_distance, (PropertyRNA *)&rna_CameraStereoData_convergence_mode,
	-1, "pivot", 3, 0, 0, 0, "Pivot",
	"",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	0, -1, NULL},
	CameraStereoData_pivot_get, CameraStereoData_pivot_set, NULL, NULL, NULL, NULL, rna_CameraStereoData_pivot_items, 3, 0
};

FloatPropertyRNA rna_CameraStereoData_interocular_distance = {
	{(PropertyRNA *)&rna_CameraStereoData_convergence_distance, (PropertyRNA *)&rna_CameraStereoData_pivot,
	-1, "interocular_distance", 3, 0, 4, 0, "Interocular Distance",
	"Set the distance between the eyes - the stereo plane distance / 30 should be fine",
	0, "*",
	PROP_FLOAT, PROP_DISTANCE | PROP_UNIT_LENGTH, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	offsetof(CameraStereoSettings, interocular_distance), 5, NULL},
	CameraStereoData_interocular_distance_get, CameraStereoData_interocular_distance_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 10000.0f, 0.0f, FLT_MAX, 1.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_CameraStereoData_convergence_distance = {
	{(PropertyRNA *)&rna_CameraStereoData_use_spherical_stereo, (PropertyRNA *)&rna_CameraStereoData_interocular_distance,
	-1, "convergence_distance", 3, 0, 4, 0, "Convergence Plane Distance",
	"The converge point for the stereo cameras (often the distance between a projector and the projection screen)",
	0, "*",
	PROP_FLOAT, PROP_DISTANCE | PROP_UNIT_LENGTH, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	offsetof(CameraStereoSettings, convergence_distance), 5, NULL},
	CameraStereoData_convergence_distance_get, CameraStereoData_convergence_distance_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0000100000f, 15.0f, 0.0000100000f, FLT_MAX, 1.0f, 3, 0.0f, NULL
};

BoolPropertyRNA rna_CameraStereoData_use_spherical_stereo = {
	{(PropertyRNA *)&rna_CameraStereoData_use_pole_merge, (PropertyRNA *)&rna_CameraStereoData_convergence_distance,
	-1, "use_spherical_stereo", 3, 0, 0, 0, "Spherical Stereo",
	"Render every pixel rotating the camera around the middle of the interocular distance",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	0, -1, NULL},
	CameraStereoData_use_spherical_stereo_get, CameraStereoData_use_spherical_stereo_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_CameraStereoData_use_pole_merge = {
	{(PropertyRNA *)&rna_CameraStereoData_pole_merge_angle_from, (PropertyRNA *)&rna_CameraStereoData_use_spherical_stereo,
	-1, "use_pole_merge", 3, 0, 0, 0, "Use Pole Merge",
	"Fade interocular distance to 0 after the given cutoff angle",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	0, -1, NULL},
	CameraStereoData_use_pole_merge_get, CameraStereoData_use_pole_merge_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

FloatPropertyRNA rna_CameraStereoData_pole_merge_angle_from = {
	{(PropertyRNA *)&rna_CameraStereoData_pole_merge_angle_to, (PropertyRNA *)&rna_CameraStereoData_use_pole_merge,
	-1, "pole_merge_angle_from", 3, 0, 4, 0, "Pole Merge Start Angle",
	"Angle at which interocular distance starts to fade to 0",
	0, "*",
	PROP_FLOAT, PROP_ANGLE | PROP_UNIT_ROTATION, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	offsetof(CameraStereoSettings, pole_merge_angle_from), 5, NULL},
	CameraStereoData_pole_merge_angle_from_get, CameraStereoData_pole_merge_angle_from_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.5707963705f, 0.0f, 1.5707963705f, 10.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_CameraStereoData_pole_merge_angle_to = {
	{NULL, (PropertyRNA *)&rna_CameraStereoData_pole_merge_angle_from,
	-1, "pole_merge_angle_to", 3, 0, 4, 0, "Pole Merge End Angle",
	"Angle at which interocular distance is 0",
	0, "*",
	PROP_FLOAT, PROP_ANGLE | PROP_UNIT_ROTATION, NULL, 0, {0, 0, 0}, 0,
	NULL, 85393408, NULL, NULL,
	offsetof(CameraStereoSettings, pole_merge_angle_to), 5, NULL},
	CameraStereoData_pole_merge_angle_to_get, CameraStereoData_pole_merge_angle_to_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.5707963705f, 0.0f, 1.5707963705f, 10.0f, 3, 0.0f, NULL
};

StructRNA RNA_CameraStereoData = {
	{(ContainerRNA *)&RNA_GameCameraViewportData, (ContainerRNA *)&RNA_Camera,
	NULL,
	{(PropertyRNA *)&rna_CameraStereoData_rna_properties, (PropertyRNA *)&rna_CameraStereoData_pole_merge_angle_to}},
	"CameraStereoData", NULL, NULL, 516, NULL, "Stereo",
	"Stereoscopy settings for a Camera data-block",
	"*", 17,
	NULL, (PropertyRNA *)&rna_CameraStereoData_rna_properties,
	NULL,
	&RNA_Camera,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Viewport */
CollectionPropertyRNA rna_GameCameraViewportData_rna_properties = {
	{(PropertyRNA *)&rna_GameCameraViewportData_rna_type, NULL,
	-1, "rna_properties", 0, 0, 1, 0, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GameCameraViewportData_rna_properties_begin, GameCameraViewportData_rna_properties_next, GameCameraViewportData_rna_properties_end, GameCameraViewportData_rna_properties_get, NULL, NULL, GameCameraViewportData_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_GameCameraViewportData_rna_type = {
	{(PropertyRNA *)&rna_GameCameraViewportData_left_ratio, (PropertyRNA *)&rna_GameCameraViewportData_rna_properties,
	-1, "rna_type", 8912896, 0, 0, 0, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GameCameraViewportData_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

FloatPropertyRNA rna_GameCameraViewportData_left_ratio = {
	{(PropertyRNA *)&rna_GameCameraViewportData_right_ratio, (PropertyRNA *)&rna_GameCameraViewportData_rna_type,
	-1, "left_ratio", 3, 0, 4, 0, "Left Ratio",
	"Set camera viewport left to a ratio of the entire viewport width",
	0, "*",
	PROP_FLOAT, PROP_FACTOR | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	offsetof(GameCameraViewportSettings, leftratio), 5, NULL},
	GameCameraViewportData_left_ratio_get, GameCameraViewportData_left_ratio_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_GameCameraViewportData_right_ratio = {
	{(PropertyRNA *)&rna_GameCameraViewportData_bottom_ratio, (PropertyRNA *)&rna_GameCameraViewportData_left_ratio,
	-1, "right_ratio", 3, 0, 4, 0, "Right Ratio",
	"Set camera viewport right to a ratio of the entire viewport width",
	0, "*",
	PROP_FLOAT, PROP_FACTOR | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	offsetof(GameCameraViewportSettings, rightratio), 5, NULL},
	GameCameraViewportData_right_ratio_get, GameCameraViewportData_right_ratio_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 1.0f, NULL
};

FloatPropertyRNA rna_GameCameraViewportData_bottom_ratio = {
	{(PropertyRNA *)&rna_GameCameraViewportData_top_ratio, (PropertyRNA *)&rna_GameCameraViewportData_right_ratio,
	-1, "bottom_ratio", 3, 0, 4, 0, "Bottom Ratio",
	"Set camera viewport bottom to a ratio of the entire viewport height",
	0, "*",
	PROP_FLOAT, PROP_FACTOR | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	offsetof(GameCameraViewportSettings, bottomratio), 5, NULL},
	GameCameraViewportData_bottom_ratio_get, GameCameraViewportData_bottom_ratio_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_GameCameraViewportData_top_ratio = {
	{NULL, (PropertyRNA *)&rna_GameCameraViewportData_bottom_ratio,
	-1, "top_ratio", 3, 0, 4, 0, "Top Ratio",
	"Set camera viewport top to a ratio of the entire viewport height",
	0, "*",
	PROP_FLOAT, PROP_FACTOR | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	offsetof(GameCameraViewportSettings, topratio), 5, NULL},
	GameCameraViewportData_top_ratio_get, GameCameraViewportData_top_ratio_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 1.0f, NULL
};

StructRNA RNA_GameCameraViewportData = {
	{(ContainerRNA *)&RNA_ClothSolverResult, (ContainerRNA *)&RNA_CameraStereoData,
	NULL,
	{(PropertyRNA *)&rna_GameCameraViewportData_rna_properties, (PropertyRNA *)&rna_GameCameraViewportData_top_ratio}},
	"GameCameraViewportData", NULL, NULL, 516, NULL, "Viewport",
	"Game custom camera viewport settings",
	"*", 17,
	NULL, (PropertyRNA *)&rna_GameCameraViewportData_rna_properties,
	NULL,
	&RNA_Camera,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

