#!E:\Mundo Aberto Game Dev\0.0.1 Protótipo\2.79\python\bin\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
